#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Apr 07, 2023 02:53:11 PM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_dft_desc) $desc
set vTcl(actual_gui_font_dft_name) [font create {*}$desc]
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #d9d9d9
set vTcl(actual_gui_menu_analog) #d9d9d9
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #d9d9d9
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #919191 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 723x506+715+350
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Text Widget Demo"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Main" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 435 -highlightcolor black -width 555 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra47
    vTcl::widgets::ttk::scrolledtext::CreateCmd "$site_3_0.scr48" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr48" "Scrolledtext1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A

    $site_3_0.scr48.01 configure -background white \
        -exportselection 0 \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap word
    vTcl:copy_lock $site_3_0.scr48
    place $site_3_0.scr48 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra47
    button "$top.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background #919191 -borderwidth 2 -command "on_btnExit" \
        -compound left -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text "Exit" 
    vTcl:DefineAlias "$top.but49" "btnExit" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    frame "$top.fra50" \
        -borderwidth 2 -relief sunken -background #919191 -height 55 \
        -highlightcolor black -width 715 
    vTcl:DefineAlias "$top.fra50" "Frame2" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra50
    label "$site_3_0.lab47" \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background #a1a1a1 -compound left \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text "Label" -textvariable "CurrentLocation" 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.lab47
    label "$site_3_0.lab48" \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background #a1a1a1 -compound left \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text "Label" -textvariable "CurrentSelection" 
    vTcl:DefineAlias "$site_3_0.lab48" "Label2" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.lab48
    place $site_3_0.lab47 \
        -in $site_3_0 -x 4 -y 4 -width 196 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 203 -y 4 -width 246 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra50
    button "$top.but48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background #919191 -borderwidth 2 -command "on_btnLoadFile" \
        -compound left -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Load FIle" 
    vTcl:DefineAlias "$top.but48" "btnLoadFile" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    vTcl::widgets::core::popup::createCmd "$top.pop49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_fg) -tearoff 1 
    global vTcl
    set val vTcl($top.pop49,-proc)
    set vTcl($top.pop49,-proc) popup1
    namespace eval ::widgets::$top.pop49 {}
    set ::widgets::$top.pop49::ClassOption(-proc) popup1
    set ::widgets::$top.pop49::options(-proc) popup1
    set ::widgets::$top.pop49::save(-proc) 1
    vTcl:DefineAlias "$top.pop49" "Popupmenu1" vTcl:WidgetProc "" 1
### SPOT dump_widget_opt A
    $top.pop49 add command \
        -compound left -label "Copy" 
    $top.pop49 add command \
        -compound left -label "Cut" 
    $top.pop49 add command \
        -compound left -label "Paste" 
    $top.pop49 add separator \
        
    $top.pop49 add cascade \
        -menu ".top1.pop49.men50" -compound left -label "Bold" 
    set site_3_0 $top.pop49
    menu "$site_3_0.men50" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men50 add command \
        -command "#on_popBoldOn" -compound left -label "Bold On" 
    $site_3_0.men50 add command \
        -command "#on_popBoldOff" -compound left -label "Bold OFf" 
    $top.pop49 add cascade \
        -menu ".top1.pop49.men51" -compound left -label "Italic" 
    set site_3_0 $top.pop49
    menu "$site_3_0.men51" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men51 add command \
        -command "#on_popItalicOn" -compound left -label "Italic On" 
    $site_3_0.men51 add command \
        -command "#on_popItalicOff" -compound left -label "Italic Off" 
    $top.pop49 add cascade \
        -menu ".top1.pop49.men47" -compound left -label "Bold AND Italic" 
    set site_3_0 $top.pop49
    menu "$site_3_0.men47" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men47 add command \
        -command "#on_popBoldItalicOn" -compound left -label "Bold Italic On" 
    $site_3_0.men47 add command \
        -command "#on_popBoldItalicOff" -compound left \
        -label "Bold Italic Off" 
    $top.pop49 add separator \
        
    $top.pop49 add cascade \
        -menu ".top1.pop49.men48" -compound left -label "Colored Text" 
    set site_3_0 $top.pop49
    menu "$site_3_0.men48" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men48 add command \
        -command "#on_popColorRed" -compound left -label "Red" 
    $site_3_0.men48 add command \
        -command "#on_popRemoveRed" -compound left -label "Remove Red" 
    $site_3_0.men48 add command \
        -command "#on_popColorGreen" -compound left -label "Green" 
    $site_3_0.men48 add command \
        -command "#on_popRemoveGreen" -compound left -label "Remove Green" 
    $site_3_0.men48 add command \
        -command "#on_popColorBlue" -compound left -label "Blue" 
    $site_3_0.men48 add command \
        -command "#on_popRemoveBlue" -compound left -label "Remove Blue" 
    $top.pop49 add command \
        -compound left -label "Close Menu" 
    button "$top.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background #919191 -borderwidth 2 -command "on_btnGoToTop" \
        -compound left -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Go To Top" 
    vTcl:DefineAlias "$top.but47" "btnGoToTop" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    button "$top.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background #919191 -borderwidth 2 -command "on_btnGotoBottom" \
        -compound left -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Go To Bottom" 
    vTcl:DefineAlias "$top.but50" "btnGoToBottom" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    button "$top.but51" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background #919191 -borderwidth 2 -command "on_btnInsertImage" \
        -compound left -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Insert Image" 
    vTcl:DefineAlias "$top.but51" "btnInsertImage" vTcl:WidgetProc "Main" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 4 -y 4 -width 555 -relwidth 0 -height 435 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 581 -y 30 -width 125 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra50 \
        -in $top -x 4 -y 445 -width 715 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 581 -y 80 -width 123 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 581 -y 130 -width 123 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 581 -y 180 -width 123 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 581 -y 230 -width 123 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

